version: '3.8'

services:
  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://host.docker.internal:8001
      - VITE_WS_BASE_URL=ws://host.docker.internal:8001
    extra_hosts:
      - "host.docker.internal:host-gateway"
    stdin_open: true
    tty: true
